version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "0.0.0.0:8080:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
    depends_on:
      - node

  node:
    build: .
    volumes:
      - ./commands.txt:/app/commands.txt
